"""项目参数汇总。

灰度参数的唯一来源在 gray.py；本文件汇总跨模块使用的参数与巡台电机初值。
"""

from gray import (  # noqa: F401
    GRAY_CENTER_REFERENCE,
    GRAY_CHANNELS,
    GRAY_EDGE_REFERENCE,
    GRAY_FILTER_WINDOW,
    GRAY_NEAR_EDGE_CLEAR,
    GRAY_NEAR_EDGE_ENTER,
    GRAY_WHITE_CLEAR,
    GRAY_WHITE_ENTER,
    GRAY_WHITE_REFERENCE,
)

# 电机值没有同步运动采样，以下是基于 up_controller 现有量级的保守首轮台架值。
PATROL_CRUISE_LINEAR = 155
PATROL_CRUISE_TURN = 25       # 正值：左轮更快，顺时针缓弧
PATROL_SLOW_LINEAR = 105
PATROL_SLOW_TURN = 35
PATROL_RECENTER_LINEAR = 135
PATROL_RECENTER_TURN = 150
PATROL_WHITE_LINEAR = 210
PATROL_WHITE_TURN = 170
PATROL_COMMAND_LIMIT = 260

PATROL_WHITE_CONFIRM = 2
PATROL_NEAR_CONFIRM = 3
PATROL_WHITE_MIN_SECONDS = 0.35
PATROL_WHITE_MAX_SECONDS = 1.00
PATROL_RECENTER_MIN_SECONDS = 0.25
PATROL_RECENTER_MAX_SECONDS = 0.90
PATROL_STALE_SECONDS = 0.20
